name: Cleanup NPM Aliases

on:
  delete:
    branches:
      - 'feature/**'
      - 'feat/**'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Remove NPM dist-tag
        run: |
          BRANCH_NAME=$(echo "${{ github.event.ref }}" | sed 's/refs\/heads\///g' | sed 's/\//-/g')
          npm dist-tag rm npm-demo-semantic-release $BRANCH_NAME || true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}